#!/bin/bash
# Prevents direct editing of auto-generated RBS type definition files.
# Type definitions in */sig/ directories are managed by PostToolUse hooks.
# Hand-written stubs for third-party gems under sig/gems/ are exempt.

# Hook input is JSON from stdin
input=$(cat)
tool_name=$(echo "$input" | jq -r '.tool_name // ""')

# Block Write/Edit operations on sig/ files
if [[ "$tool_name" == "Write" || "$tool_name" == "Edit" ]]; then
    file_path=$(echo "$input" | jq -r '.tool_input.file_path // ""')

    if [[ "$file_path" == */sig/gems/* || "$file_path" == sig/gems/* ]]; then
        exit 0
    fi

    if [[ "$file_path" == */sig/* || "$file_path" == sig/* ]]; then
        echo "❌ ERROR: Direct editing of generated sig/ files is not allowed." >&2
        echo "📝 This repository's own types are generated: fix the inline RBS comments in the .rb file." >&2
        echo "💡 Hand-written files are allowed only under sig/gems/ (stubs for third-party gems)." >&2
        exit 2
    fi
fi

# Block manual rbs-inline execution
if [[ "$tool_name" == "Bash" ]]; then
    command=$(echo "$input" | jq -r '.tool_input.command // ""')

    # Match rbs-inline only at a command position, not as an argument.
    rbs_inline_re=$'(^|[;&|(\n])[[:space:]]*(bundle[[:space:]]+exec[[:space:]]+)?([^[:space:]]*/)?rbs-inline([[:space:]]|[;&|)]|$)'

    if [[ "$command" =~ $rbs_inline_re ]]; then
        echo "❌ ERROR: Manual rbs-inline execution is not allowed." >&2
        echo "🔄 Type definitions are auto-generated by hooks." >&2
        exit 2
    fi
fi

exit 0
