AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

plugins:
  - rubocop-numbered-params
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/rbs_activesupport/ast.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/rbs_activesupport/ast.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "lib/rbs_activesupport/ast.rb"

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AccessorGrouping:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/OneClassPerFile:
  Exclude:
    - spec/**/*.rb

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation
  Exclude:
    - "spec/**/*"

Style/RbsInline/RedundantTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/RbsInline/UntypedInstanceVariable:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
