AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/rbs_activesupport/ast.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/rbs_activesupport/ast.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "lib/rbs_activesupport/ast.rb"

Style/AccessorGrouping:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
