module RbsActivesupport
  class MethodSearcher
    attr_reader rbs_builder: RBS::DefinitionBuilder

    def initialize: (RBS::DefinitionBuilder rbs_builder) -> void
    def method_types_for: (Delegate delegate) -> Array[String]

    private

    def detect_return_type_names: (Array[RBS::MethodType] delegate_to) -> Array[RBS::TypeName]
    def lookup_method_types: (RBS::TypeName namespace, Symbol method) -> Array[RBS::MethodType]
  end
end
