module RbsActivesupport
  class RakeTask < Rake::TaskLib
    attr_accessor name: Symbol
    attr_accessor signature_root_dir: Pathname

    @rbs_builder: RBS::DefinitionBuilder

    def initialize: (?Symbol name) ?{ (self) -> void } -> void
    def define_setup_task: () -> void
    def define_generate_task: () -> void
    def define_clean_task: () -> void

    private

    def rbs_builder: () -> RBS::DefinitionBuilder
  end
end
