module RbsActivesupportDelegate
  module AST
    def eval_args: (Array[untyped] args) -> Array[Array[Symbol?]]
    def eval_args_with_options: (Array[untyped] args) -> [Array[Symbol], Hash[Symbol, untyped]]
    def eval_node: (untyped node) -> untyped
  end
end
