module RbsActivesupportDelegate
  class DeclarationBuilder
    type t = Delegate

    include AST

    attr_reader method_searcher: MethodSearcher

    def initialize: (MethodSearcher method_searcher) -> void
    def build: (RBS::Namespace namespace, Array[Parser::MethodCall] method_calls) -> [Array[String], Array[String]]

    private

    def build_method_calls: (RBS::Namespace namespace, Array[Parser::MethodCall] method_calls) -> Array[t]
    def build_delegate: (RBS::Namespace namespace, Parser::MethodCall method_calls) -> Array[Delegate]
    def render: (t decl) -> String
    def render_delegate: (Delegate decl) -> String
  end
end
