name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rbs collection up
      run: bundle exec rbs collection install --frozen
    - name: Run the default task
      run: bundle exec rake
    - name: Run rspec
      run: bundle exec rspec
    - name: Run rbs validate
      run: bundle exec rbs =i sig validate --silent
    - name: Run steep
      run: bundle exec steep check
