name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rbs collection up
      run: bundle exec rbs collection install --frozen
    - name: Run the default task
      run: bundle exec rake
    - name: Run rspec
      run: bundle exec rspec
    - name: Run rbs validate
      run: bundle exec rbs =i sig validate --silent
    - name: Run steep
      run: bundle exec steep check
